trigger:
  - main  # O la rama que uses para despliegue

pool:
  vmImage: 'ubuntu-latest'

# # Evita que otros pipelines se ejecuten en paralelo
# concurrency:
#   cancelInProgress: false  # no cancela pipelines anteriores
#   group: angular-deployment-lock  # asegura que uno a la vez use este grupo

variables:
  buildDir: dist  # carpeta donde Angular genera el build
  nodeVersion: '18.x'

stages:
  - stage: Build
    jobs:
      - job: BuildAngularApp
        steps:
          - task: NodeTool@0
