stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageDisplayName }}
    #group:
    #pool:
    jobs:
      - job: build
        displayName: Build ${{ parameters.stageDisplayName }}
        steps:
          # Install node
          - task: NodeTool@0
            displayName: "Install Node.js"
            inputs:
              versionSpec: $(nodeVersion)

          # Save the cache
          - task: Cache@2
            inputs:
              key: $(NPM_CACHE_KEYS)
              restoreKeys: |
                npm | "$(Agent.OS)"
              path: $(NPM_CACHE_FOLDER)
              cacheHitVar: NPM_CACHE_RESTORED
            displayName: "Cache Npm Dependencies"

          # Install dependencies
          - script: |
              npm install -g @angular/cli@${{ variables.angularCliVersion}}
              npm ci
            displayName: "Angular CLI ${{ variables.angularCliVersion}} and Install dependencies"

          - script: ${{ variables.appBuildCommandProd }}
            displayName: "Build ${{ variables.appName }}"

          # Archive build artifacts
          - task: ArchiveFiles@2
            displayName: "Archive Build Artifacts ${{ variables.appArtifactName }}"
            inputs:
              rootFolderOrFile: "$(System.DefaultWorkingDirectory)/dist/${{ variables.appArtifactPath }}"
              includeRootFolder: false
              archiveType: "zip"
              archiveFile: "$(Build.ArtifactStagingDirectory)/build/${{ variables.appArtifactPath }}-$(Build.BuildId).zip"
              replaceExistingArchive: true

      - job: publish
        displayName: Publish ${{ variables.stageDisplayName }}
        dependsOn: build
        #pool:
        steps:
          # Publish build artifacts
          - task: PublishBuildArtifacts@1
            displayName: Publish Build Artifacts
            inputs:
              pathtoPublish: "$(Build.ArtifactStagingDirectory)/build/${{ variables.appArtifactPath }}-$(Build.BuildId).zip"
              artifactName: "drop-${{ variables.appArtifactName }}"
              publishLocation: "Container"
