stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageDisplayName }}
    dependsOn: ${{ parameters.stageDependsOn}}
    condition: succeeded()
    jobs:
      - deployment: DeployWebApp
        displayName: "Deploy $(webAppName)"
        environment: ${{ parameters.environmentName}}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: AzureWebApp@1
                  displayName: "Azure Web App Deploy: $(webAppName)"
                  inputs:
                    azureSubscription: $(appAzureSubscription)
                    appType: webAppLinux
                    appName: $(webAppName)
                    package: $(Pipeline.Workspace)/drop/${{ parameters.appArtifactPath }}-$(Build.BuildId).zip
                    runtimeStack: $(deployRuntimeStack)
