stages:
  - stage: ${{ parameters.stageName }}
    displayName: ${{ parameters.stageDisplayName }}
    dependsOn: build
    condition: succeeded()
    jobs:
      - deployment: DeployWebApp
        displayName: "Deploy $(appName)"
        environment: ${{ parameters.environmentName}}
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  inputs:
                    buildType: "current"
                    artifactName: "drop"
                    targetPath: "$(System.DefaultWorkingDirectory)"
                - task: AzureWebApp@1
                  displayName: "Azure Web App Deploy: ${{ parameters.appName }}"
                  inputs:
                    azureSubscription: $(azureSubscription)
                    appType: webAppLinux
                    appName: $(appName)
                    package: $(Pipeline.Workspace)/drop/${{ parameters.appArtifactPath }}-$(Build.BuildId).zip
                    runtimeStack: $(deployRuntimeStack)
