trigger:
  branches:
    include:
      - main
      - feature/*
      - fix/*
  paths:
    include:
      - "mfe-host/*"

pool:
  vmImage: $(vmImageName)

variables:
  - template: variables-template
    parameters:
      appName: "mfe-host"
      appArtifactName: "mfe-host"
      appArtifactPath: "mfe-host"
      environmentName: "mfe-host"

stages:
  - template: build-mfe.yml
    parameters:
      stageName: build-${{ variables.appArtifactName }}
      stageDisplayName: Build and publish artifact ${{ variables.appName }}

  - template: deploy-environment-function-type.yml
    parameters:
      stageName: dev-${{ variables.appArtifactName }}
      stageDisplayName: Dev environment ${{ variables.appName }}

  - template: deploy-environment-web-app-type.yml
    parameters:
      stageName: deploy-${{ variables.appArtifactName }}
      stageDisplayName: Deploy stage ${{ variables.appName }}
