trigger:
  branches:
    include:
      - main
      - feature/*
      - fix/*
  paths:
    include:
      - "mfe-auth/*"

variables:
  - template: templates/variables-template.yml
    parameters:
      APP_NAME: "mfe-auth"
      APP_ARTIFACT_NAME: "mfe-auth"
      APP_ARTIFACT_PATH: "mfe-auth"
      ENVIRONMENT_NAME: "mfe-auth"
      BUILD_PREFIX_COMMAND: "mfe-auth"

pool:
  vmImage: $(vmImageName)

stages:
  - template: templates/build-template.yml
    parameters:
      stageName: build_mfe_host
      stageDisplayName: ${{ variables.appName }}
      env:
        MS_API_URL: $(MS_API_URL)

  # - template: templates/deploy-function-type-template.yml
  #   parameters:
  #     stageName: dev_mfe_host
  #     stageDisplayName: Dev environment ${{ variables.appName }}

  # - template: templates/deploy-web-app-type-template.yml
  #   parameters:
  #     stageName: deploy_mfe_host
  #     stageDisplayName: Deploy stage ${{ variables.appName }}
