trigger:
  branches:
    include:
      - main
      - feature/*
      - fix/*
  paths:
    include:
      - "projects/mfe-host/*"

variables:
  - template: templates/variables-template.yml
    parameters:
      APP_NAME: "mfe-host"
      APP_ARTIFACT_NAME: "mfe-host"
      APP_ARTIFACT_PATH: "mfe-host"
      ENVIRONMENT_NAME: "mfe-host"
      BUILD_PREFIX_COMMAND: "mfe-host"
      AZURE_SUBSCRIPTION: "Azure for Students(1)(121f6adb-a21e-4a35-a892-c1609c3b5952)"
      DEPLOY_APP_NAME: "affi-challenge-web"
      DEPLOY_APP_TYPE: "webApp"

# parameters:
#   - name: environmentVariables
#     type: object
#     default:
#       - variableName: "MS_API_URL"
#         variableValue: $(MS_API_URL)
#       - variableName: "MFE_AUTH_URL"
#         variableValue: $(MFE_AUTH_URL)

pool:
  vmImage: $(vmImageName)

stages:
  - template: templates/build-template.yml
    parameters:
      stageName: build_mfe_host
      stageDisplayName: ${{ variables.appName }}
      # environmentVariables: ${{ parameters.environmentVariables }}
      set_env:
        # - script: echo "##vso[task.setvariable variable=MFE_AUTH_URL]$(MFE_AUTH_URL)"
        #   displayName: "set env MFE_AUTH_URL"
        - script: $(appBuildCommandProd)
          displayName: "Build ${{ variables.appName }}"
          env:
            MFE_AUTH_URL: $(MFE_AUTH_URL)

  # - template: templates/deploy-function-type-template.yml
  #   parameters:
  #     stageName: dev_mfe_host
  #     stageDisplayName: Dev environment ${{ variables.appName }}

  - template: templates/deploy-web-app-type-template.yml
    parameters:
      stageName: deploy_mfe_host
      stageDisplayName: Deploy stage ${{ variables.appName }}
      environmentName: "stage"
      stageDependsOn: build_mfe_host
      deployAppName: ${{ variables.deployAppName }}
