trigger:
  branches:
    include:
      - main
      - feature/*
      - fix/*
  paths:
    include:
      - "mfe-host/*"

variables:
  - template: templates/variables-template.yml
    parameters:
      appName: "mfe-host"
      appArtifactName: "mfe-host"
      appArtifactPath: "mfe-host"
      environmentName: "mfe-host"

pool:
  vmImage: $(vmImageName)

stages:
  - template: templates/build-template.yml
    parameters:
      stageName: build_mfe_host
      stageDisplayName: Build and publish artifact ${{ variables.appName }}
      env:
        MS_API_URL: $(MS_API_URL)

  # - template: templates/deploy-function-type-template.yml
  #   parameters:
  #     stageName: dev_mfe_host
  #     stageDisplayName: Dev environment ${{ variables.appName }}

  # - template: templates/deploy-web-app-type-template.yml
  #   parameters:
  #     stageName: deploy_mfe_host
  #     stageDisplayName: Deploy stage ${{ variables.appName }}
